name: Deploy Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Firebase Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: setup enviroment
        run: |
          echo ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }} >> .env
          echo ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }} >> .env
          echo ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }} >> .env

      - name: install package
        run: |
          yarn install --frozen-lockfile

      - name: generate Next.js
        run: |
          yarn build

      - name: deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
